spring:
  application:
    name: SpringSecurityLab

  profiles:
    group:
      local: local
      prod: prod

server:
  port: 8080

jwt:
  expiration:
    access: 600000 # 10 min.
    refresh: 864000000 # 10 days